#+TITLE: IntelliJ's IdeaVim Configuration
#+property: header-args:bash :tangle .ideavimrc
#+startup: fold
The configuration is saved in the dotfile .ideavimrc.
Those Keybindings base on [[https://github.com/MarcoIeni/intellimacs#intellimacs][Intellimacs]], which base on the [[https://github.com/syl20bnr/spacemacs][Spacemacs]]. My own Keybindings are inspired by [[https://github.com/hlissner/doom-emacs#doom-emacs][Doom Emacs]]

* Table of Contents :TOC_3:noexport:
- [[#default][Default]]
  - [[#import-intellijmacs][Import Intellijmacs]]
  - [[#settings][Settings]]
  - [[#keymappings][Keymappings]]
    - [[#method-motions-and-operators][Method motions and operators]]
    - [[#misc][Misc]]
- [[#plugins][Plugins]]
  - [[#load][Load]]
  - [[#settings-empty][Settings (empty)]]
  - [[#keymappings-1][Keymappings]]
- [[#ideavim][IdeaVim]]
  - [[#settings-1][Settings]]
  - [[#keymappings-2][Keymappings]]
    - [[#bookmark][Bookmark]]
    - [[#buffer][Buffer]]
    - [[#code][Code]]
    - [[#database][Database]]
    - [[#debug][Debug]]
    - [[#file][File]]
    - [[#gitversions-control][Git/Versions control]]
    - [[#goto][Goto]]
    - [[#gradle][Gradle]]
    - [[#help-and-hierarchy][Help and Hierarchy]]
    - [[#insertions][Insertions]]
    - [[#misc-unsorted][Misc (Unsorted)]]
    - [[#notifications][Notifications]]
    - [[#refactor][Refactor]]
    - [[#replace-hotkeysshortcuts][Replace hotkeys/shortcuts]]
    - [[#run][Run]]
    - [[#window][Window]]
- [[#usefull-links][Usefull Links]]
- [[#ideas--todos][Ideas / Todos]]
  - [[#mark-line-_v---vv--recherchieren-ob-es-bereits-defaults-dafür-gibt--ggf-auch-in-doom][Mark Line. "_v$" -> "vv" . Recherchieren ob es bereits defaults dafür gibt . Ggf auch in doom..]]
  - [[#in-insert-c-v-for-paste-or-c-r-c-r-or-c-r-c-e][in insert: C-v for paste? or C-r C-r? or C-r C-e?]]
  - [[#misc-1][Misc]]

* Default
** Import Intellijmacs
First, so it can be overwritten
#+begin_src bash
source ~/.intellimacs/spacemacs.vim
source ~/.intellimacs/extra.vim
source ~/.intellimacs/major.vim
source ~/.intellimacs/hybrid.vim
#+end_src
** Settings
#+begin_src bash
let mapleader = " "
set nu "rnu
set clipboard=unnamedplus
set ignorecase
set smartcase
set hlsearch
set incsearch ""highlight halfway typing
set visualbell
set noerrorbells
#+end_src
** Keymappings
*** Method motions and operators
#+begin_src bash
nnoremap ym [M+eV]My
nnoremap dm [M+eV]Md
nnoremap vm [M+eV]M
#+end_src
*** Misc
#+begin_src bash
nmap , <leader>m
vmap , <leader>m
nnoremap Y yg_
nmap gR gr$
nnoremap y_ y^
nnoremap d_ d^
nnoremap c_ c^
nnoremap <leader>. @:
nnoremap <leader>sc :nohl<CR>
nnoremap <Leader>sr :%s///gcI<left><left><left><left><left>
vnoremap sr y:%s///gcI<left><left><left><left><left><C-r>0<right>
vnoremap ss y/<C-r>0<CR>
#+end_src
* Plugins
Sometimes the plugins doesn't load. Then you should use their name and not alias, which you find here: VimExtensions.xml -> https://github.com/JetBrains/ideavim/blob/master/resources/META-INF/includes/VimExtensions.xml
** Load
#+begin_src bash
set surround
set commentary
set easymotion
set multiple-cursors "<A-n>, <A-x>, <A-p>, g<A-n>
set NERDTree
set textobj-indent "set vim-indent-object is not working
set textobj-entire
set argtextobj
set ReplaceWithRegister
set highlightedyank
set exchange
#+end_src
** Settings (empty)
#+begin_src bash
#+end_src
** Keymappings
#+begin_src bash
nmap s <Plug>(easymotion-s2)
nmap S <Plug>(easymotion-sl2)
"map <Leader> <Plug>(easymotion-prefix) "-> only one <Leader>, instead of <Leader><Leader>
#+end_src
* IdeaVim
** Settings
#+begin_src bash
set ideajoin
set idearefactormode=keep
set clipboard+=ideaput
#+end_src
** Keymappings
*** Bookmark
#+begin_src bash
nnoremap <leader><enter> :action ShowBookmarks<CR>
nnoremap <leader>bm :action ToggleBookmark<CR>
#+end_src
*** Buffer

Show recent Files | "Switch Workspace Buffer"

#+begin_src bash
nnoremap <Leader>, :action RecentFiles<CR>
vnoremap <Leader>, :action RecentFiles<CR>
#+end_src

#+begin_src bash
nnoremap <leader>bs :action NewScratchFile<CR>
vnoremap <leader>bs :action NewScratchFile<CR>
nnoremap <leader>bc :action Scratch.ChangeLanguage<CR>
vnoremap <leader>bc :action Scratch.ChangeLanguage<CR>
#+end_src
*** Code

Format Buffer/Region

#+begin_src bash
nnoremap <leader>cf :action ReformatCode<CR>
#+end_src

Optimize/Organize Imports

#+begin_src bash
nnoremap <leader>co :action OptimizeImports<CR>
#+end_src

*** Database
#+begin_src bash
nnoremap <Leader>dd :action ActivateDatabaseToolWindow<CR>
#+end_src
*** Debug
#+begin_src bash
nnoremap <leader>mds    :action ChooseDebugConfiguration<CR>
nnoremap <leader>mdi    :action StepInto<CR>
nnoremap <leader>mdd    :action DebugClass<CR>
nnoremap <leader>mdl    :action Debug<CR>
#+end_src
*** File
#+begin_src bash
nnoremap <leader><leader> :action GotoFile<CR>
nnoremap <leader>fo :action OpenFile<CR>
#+end_src
*** Git/Versions control
#+begin_src bash
nnoremap <Leader>gg :action ActivateCommitToolWindow<CR>
nnoremap <leader>go :action Vcs.QuickListPopupAction<CR>
nnoremap <leader>gf :action Git.Fetch<CR>
nnoremap <leader>gF :action Vcs.UpdateProject<CR>
nnoremap <leader>ga :action Annotate<CR>
nnoremap <leader>gl :action Vcs.Show.Log<CR>
nnoremap <leader>gf :action Vcs.ShowTabbedFileHistory<CR>
unmap <leader>gs
nnoremap <leader>gss :action Git.Stash<CR>
nnoremap <leader>gsu :action Git.Unstash<CR>
nnoremap <leader>gr :action Vcs.RollbackChangedLines<CR>
#+end_src
*** Goto
#+begin_src bash
nnoremap gi :action GotoImplementation<CR>
nnoremap gs :action GotoSuperMethod<CR>
nnoremap <Leader>mgs :action GotoSuperMethod<CR>
nnoremap gt :action GotoTest<CR>
vnoremap gt :action GotoTest<CR>
nnoremap gD :action FindUsages<CR>
vnoremap gD :action FindUsages<CR>
nnoremap g=    <C-a>
nnoremap g-    <C-x>
#+end_src
*** Gradle
#+begin_src bash
nnoremap <Leader>Gg :action ActivateGradleToolWindow<CR>
nnoremap <Leader>Gr :action ExternalSystem.ProjectRefreshAction<CR>
#+end_src
*** Help and Hierarchy
#+begin_src bash
nnoremap <Leader>hc :action CallHierarchy<CR>
#+end_src
*** Insertions
#+begin_src bash
nnoremap <leader>is    :action InsertLiveTemplate<CR>a
vnoremap <leader>is    <esc>:action insertlivetemplate<cr>a
#+end_src
*** Misc (Unsorted)
Show Main Menu

#+begin_src bash
nnoremap <Leader>mm :action MainMenu<CR>
#+end_src

Searches word under curser in all Files |  "Search current project for symbol at point"

#+begin_src bash
nnoremap <leader>* viw:action FindInPath<CR>
#+end_src

Reload .ideavimrc File

#+begin_src bash
nnoremap <leader>hrr    :source ~/.ideavimrc<CR>
#+end_src

Select current File in Project View

#+begin_src bash
nnoremap <leader>jd :action SelectInProjectView<CR>
#+end_src
*** Notifications
#+begin_src bash
nnoremap <leader>nc    :action CloseAllNotifications<CR>
#+end_src
*** Refactor
#+begin_src bash
"noremap <Leader>in :action Inline<CR>
nnoremap <leader>mrin    :action Inline<CR>
vnoremap <leader>mrin    <Esc>:action Inline<CR>

"noremap <Leader>ev :action IntroduceVariable<CR>
nnoremap <leader>mrev    :action IntroduceVariable<CR>
vnoremap <leader>mrev    <Esc>:action IntroduceVariable<CR>

"noremap <Leader>ep :action IntroduceParameter<CR>
nnoremap <leader>mrep    :action IntroduceParameter<CR>
vnoremap <leader>mrep    <Esc>:action IntroduceParameter<CR>

"noremap <Leader>ec :action IntroduceConstant<CR>
nnoremap <leader>mrec    :action IntroduceConstant<CR>
vnoremap <leader>mrec    <Esc>:action IntroduceConstant<CR>

"noremap <Leader>ef :action IntroduceField<CR>
nnoremap <leader>mref    :action IntroduceField<CR>
vnoremap <leader>mref    <Esc>:action IntroduceField<CR>

"noremap <Leader>em :action ExtractMethod<CR>
#+end_src
*** Replace hotkeys/shortcuts
#+begin_src bash
nnoremap <C-,> :action ShowSettings<CR>

nnoremap <C-j> :action MethodDown<CR>
nnoremap <C-k> :action MethodUp<CR>
nnoremap <A-j> :action MoveLineDown<CR>
nnoremap <A-k> :action MoveLineUp<CR>

nnoremap <A-S-j> :action MoveStatementDown<CR>
nnoremap <A-S-k> :action MoveStatementUp<CR>

nnoremap <A-h> :action MoveElementLeft<CR>
nnoremap <A-l> :action MoveElementRight<CR>

" Not working :-(
"nnoremap <C-n> :action NextDiff<CR>
"nnoremap <C-p> :action PreviousDiff<CR>
"Complete current Statement
"nnoremap <S- > :action EditorCompleteStatement<CR>
#+end_src
*** Run
#+begin_src bash
nnoremap <Leader>rr :action RunClass<CR>
nnoremap <Leader>ru :action RunClass<CR>
nnoremap <Leader>rl :action Rerun<CR>
nnoremap <Leader>rc :action RunCoverage<CR>
nnoremap <leader>rk :action Stop<CR>
nnoremap <leader>rs :action ChooseRunConfiguration<CR>
#+end_src
*** Window
#+begin_src bash
nnoremap <Leader>wm <C-W>o:action HideActiveWindow<CR>
#+end_src
* Usefull Links
- [[https://github.com/JetBrains/ideavim#ideavim][IdeaVim]]
- [[https://github.com/JetBrains/ideavim/blob/master/doc/set-commands.md#list-of-supported-set-commands][List of Supported Set Commands]]
- [[https://github.com/JetBrains/ideavim/blob/master/src/com/maddyhome/idea/vim/package-info.java][List of Supported motions and operations]]
- [[https://github.com/JetBrains/ideavim/blob/master/CHANGES.md#the-changelog][IdeaVim Changelog]]
- [[https://github.com/MarcoIeni/intellimacs][Intellimacs]]
* Ideas / Todos
** [#B] Mark Line. "_v$" -> "vv" . Recherchieren ob es bereits defaults dafür gibt . Ggf auch in doom..
** [#C] in insert: C-v for paste? or C-r C-r? or C-r C-e?
** Misc
#+begin_src bash

" ParameterInfo

" include emacs hotkeys like C-a ?  some examples -> https://khin.io/post/spacemacs-like-binding-for-idea-products/"

"<leader>mh...
"TypeHierarchyBase.BaseOnThisType
"MethodHierarchy.BaseOnThisMethod
"MethodHierarchy
"CallHierarchy.BaseOnThisMethod

"better vim camel case ]b ]w [b [w (SPC x i)


" sourround/insert with livetemplate

" jumb to next "Element". Example-> return findReference(seaShip, this::isKnExportReference, KnExportReference::knExportReference);
" C-S-h/l change method private -> public -> ...
" C-S-j/k change variable/method final/..(?)
" change C-A j/k to A j/k
" correct copy, yank, delte methode"

" vim smooth scorlling"
"introduceFunctionalVariable

" ### DISABLED #####
"nnoremap <Leader>rr :action Rerun<CR>
"nnoremap <Leader>fs :action FileStructurePopup<CR>
"nnoremap <Leader>rn :action RenameElement<CR>
"nnoremap <Leader>se :action ShowErrorDescription<CR>
"nnoremap <Leader>sb :action ToggleLineBreakpoint<CR>
"nnoremap <Leader>ne :action GotoNextError<CR>
"nnoremap <Leader>pe :action GotoPreviousError<CR>

"nnoremap <C-W>n :action ViewNavigationBar<CR>

"nnoremap <C-j> :action ChooseNextSubsequentPropertyValueEditorAction<CR>
"vnoremap <C-j> :action ChooseNextSubsequentPropertyValueEditorAction<CR>
"nnoremap <C-k> :action ChoosePrevSubsequentPropertyValueEditorAction<CR>
"vnoremap <C-k> :action ChoosePrevSubsequentPropertyValueEditorAction<CR>

"vnoremap <leader>y "+y
"nnoremap <leader>Y "+yg_
"nnoremap <leader>y "+y
"nnoremap <leader>yy "+yy
"nnoremap <leader>p "+p
"nnoremap <leader>P "+P
"noremap <leader>p "+p
"noremap <leader>P "+P
"nnoremap <leader>af :action EditorSelectWord<CR>
"vnoremap aa :action GuiDesigner.ExpandSelection<CR>
"vnoremap ab :action SmartSelect<CR>
"vnoremap ac :action TableResult.GrowSelection<CR>

"nnoremap <leader>af :action EditorSelectWord<CR>
"vnoremap aa :action GuiDesigner.ExpandSelection<CR>
"vnoremap ab :action SmartSelect<CR>
"vnoremap ac :action TableResult.GrowSelection<CR>
#+end_src
